# Name->Vishwa Bardhan Parasar     
# Regd->1841017163
# Sec-CSIT-C                        Assignment-2

# Q1.Creation of 1-array,2-D and 3-D array

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
ar=np.array([[1,2,3],[3,6,4]])
print(ar)

[[1 2 3]
 [3 6 4]]


In [3]:
a=np.array([[[1,2,3],[3,6,4],[7,9,8]]])
print(a)

[[[1 2 3]
  [3 6 4]
  [7 9 8]]]


# Q2.Different functions which can be performed on a numpy array. Write one example of each.

In [4]:
def lspace(start,stop,space):
    r1=np.linspace(start,stop,space)
    print("Linspace",r1)
    mean_value(np.linspace(start,stop,space))
    root_value(np.linspace(start,stop,space))
    increase_value(np.linspace(start,stop,space))
def mean_value(m):
    v1=np.mean(m)
    print("Mean",v1)
def root_value(r):
    v2=np.sqrt(r)
    print("Sqare root",v2)
def increase_value(inc):
    v3=inc+2
    print("Value increase in array by 2",v3)
lspace(2,10,5)    

Linspace [ 2.  4.  6.  8. 10.]
Mean 6.0
Sqare root [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Value increase in array by 2 [ 4.  6.  8. 10. 12.]


# Q3.Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [5]:
import numpy as vb
matrix=vb.random.randint(10,21,size=(3,4))
print(matrix)

[[12 18 20 10]
 [16 12 11 11]
 [13 11 15 14]]


# Q4.Write a NumPy program to create a two-dimensional array with shape (7,10) of random numbers. Select random numbers from a normal distribution (50,220).

In [6]:
matrix=vb.random.normal(50,220,size=(7,10))
print(matrix)

[[-151.00304101  -74.98512257  342.57812042  355.52183567  190.82855966
   175.13907036   47.66463268 -228.09038562  475.34295559  323.75926683]
 [ 168.24744511    1.23727566   79.46671633  118.12143656  507.10120446
   344.62507526  211.13648833  -37.55271946  204.5792922  -247.06692321]
 [  56.32680339  294.4892473  -409.42111154  194.36304203 -145.07744375
    87.79230525   12.52824053   31.45505382   84.50004575 -409.58099544]
 [   4.25556993  425.93870478   21.3285662   -27.17740364 -359.96618908
   107.76481945  223.87823469  448.18553653  118.38571968  516.01584562]
 [ 243.74409404  113.72445442   -4.6725582  -130.60821322 -264.30438565
  -473.83162408 -109.76108388  355.68457381 -332.34160669 -295.53144125]
 [-137.93781779   81.60269881   67.99644385  130.16681492 -402.40474013
   -18.22279766  -44.03068588  679.91543854 -132.8245335   253.5475544 ]
 [-271.13785925  251.79344222 -272.65727877  496.58089466   51.94277288
    66.7922889   379.32275372  126.56110093  142.8449842  

# 

# 